config/routes.rb
PageFetcher::Application.routes.draw do

  root :to => 'facebook_users#index'
  resources :facebook_users do
    member do
      get 'feeds'
    end
  end

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

end

app/models/facebook_user.rb
class FacebookUser < ActiveRecord::Base
  attr_accessible :name, :image_url, :identity
  
  validates_uniqueness_of :identity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def has_access_token?
  	session[:access_token].present?
  end
end

app/controllers/facebook_users_controller.rb
class FacebookUsersController < ApplicationController

	before_filter :require_token, :only => [:create, :feeds]

	def index
		@facebook_user = FacebookUser.new
	end

	def create
		identity = params[:facebook_user][:identity]
		if FacebookUser.find_by_identity(identity).nil?
			if (Facebook.validate_identity(identity))
	  		@fb_user = FacebookUser.new(Facebook.get_user_info(identity))
	  		@fb_user.save
	  	else
	  		flash[:error] = "The identity is invalid"
	  	end
	  else
	  	flash[:error] = "The user existed!"
	  end
  	redirect_to root_path
	end

	def feeds
		identity = FacebookUser.find(params[:id]).identity
		@feed_owner = Facebook.get_user_info(identity)
		feeds = Facebook.get_feeds(identity,session[:access_token])
		@feeds = []
		feeds.each do |feed|
			from_user = Facebook.get_user_info(feed['from']['id'])
			timestamp = DateTime.parse(feed['created_time']).to_time.to_i
			@feeds.push({from_image_url: from_user[:image_url], from_name: from_user[:name], message: feed['message'], created_at: timestamp})
		end
	end

	private
 
  def require_token
    unless has_access_token?
      flash[:error] = "You must connect with Facebook to get the access token"
      redirect_to "/auth/facebook"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		session[:access_token] = request.env['omniauth.auth'][:credentials][:token]
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facebook_users_helper.rb
module FacebookUsersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/facebook_users/feeds.html.erb
	<div class="feed-title">
		<%= image_tag @feed_owner[:image_url] , class: "feed-owner-icon"%>
		<p class="feed-owner-name"><%= @feed_owner[:name] %>'s feeds</p>
	</div>
	<% @feeds.each do |feed| %>
		<div class="feed">
			<%= image_tag feed[:from_image_url], class: "feed-user-icon" %>
			<p class="feed-user-name"><%= feed[:from_name]%></p>
			<p class="feed-user-created-at">created at <%= time_ago_in_words(feed[:created_at]) %></p>
			<p class="feed-message"><%= feed[:message] %></p>
		</div>
	<% end %>

app/views/facebook_users/index.html.erb
	<div class="page-fetcher-form">
		<div class="title">
			Page fetcher
		</div>

		<%= form_for @facebook_user do |f| %>
			<%= f.text_field :identity, :class => "identity_input" %><br/>
			<div class="info">(example: 188091757763)</div>
		  <div class="submit">
		  	<%= f.submit "add" , :class => "btn btn-default btn-lg" %>
		  </div>
		  <%= link_to "Refresh access token", "/auth/facebook" %>
		<% end %>
	</div>
	<div class="user-list">
		<% FacebookUser.all.each do |fb_user| %>
		<div class="user">
			<%= image_tag fb_user.image_url, :class => "user_icon"  %>
			<%= link_to fb_user.name,feeds_facebook_user_path(fb_user.id), :class => "user_name" %>
		</div>
		<% end %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PageFetcher</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
	  <li class="flash_error">
	    	<%= content_tag :div, msg, :id => "flash_#{name}" %>
	  </li>
  <% end %>
<% end %>

<%= yield %>

</div>

</body>
</html>